#ifndef __EXPERIMENTAL_CONSOLE_MODE_SETUP_VAR_H__
#define __EXPERIMENTAL_CONSOLE_MODE_SETUP_VAR_H__

#define EXPERIMENTAL_CONSOLE_MODE_SETUP_VAR_NAME  L"ExperimentalConsoleModeSetupVar"

#define EXPERIMENTAL_CONSOLE_MODE_SETUP_VARIABLE_GUID \
  { 0xc2db27cf, 0x28d6, 0x4e63, { 0x8d, 0xa2, 0x7a, 0xef, 0x98, 0xec, 0xea, 0x4e } }

#define EXPERIMENTAL_CONSOLE_TEXT_MODE_80X25   0x0
#define EXPERIMENTAL_CONSOLE_TEXT_MODE_80X50   0x1
#define EXPERIMENTAL_CONSOLE_TEXT_MODE_100X31  0x2

typedef struct {
  UINT8    SetupTextMode;
  UINT8    Reserved[3];
} EXPERIMENTAL_CONSOLE_MODE_SETUP_DATA;

#endif
