## @file
# GNU/Linux makefile for Python tools build.
#
# Copyright (c) 2007 - 2010, Intel Corporation. All rights reserved.<BR>
# SPDX-License-Identifier: BSD-2-Clause-Patent
#

V ?= 0
ifeq ($(V),1)
Q :=
else
Q := @
endif

all:

clean:
	$(Q)find . -name '*.pyc' -exec rm '{}' ';'

