#!/usr/bin/dh-exec

src/scripts/welcome.nsh => /usr/share/edk2/radxa/startup.nsh

src/Build/O6/*_GCC/cix_flash*.bin /usr/share/edk2/radxa/orion-o6/
src/Build/O6/*_GCC/BuildOptions /usr/share/edk2/radxa/orion-o6/
src/Build/O6/*_GCC/AARCH64/EnrollFromDefaultKeysApp.efi /usr/share/edk2/radxa/orion-o6/
src/Build/O6/*_GCC/AARCH64/VariableInfo.efi /usr/share/edk2/radxa/orion-o6/
src/Build/O6/*_GCC/AARCH64/Shell.efi /usr/share/edk2/radxa/orion-o6/
src/edk2-non-osi/Platform/CIX/Sky1/FlashTool/* /usr/share/edk2/radxa/orion-o6/
src/scripts/startup.nsh /usr/share/edk2/radxa/orion-o6/

src/Build/O6N/*_GCC/cix_flash*.bin /usr/share/edk2/radxa/orion-o6n/
src/Build/O6N/*_GCC/BuildOptions /usr/share/edk2/radxa/orion-o6n/
src/Build/O6N/*_GCC/AARCH64/EnrollFromDefaultKeysApp.efi /usr/share/edk2/radxa/orion-o6n/
src/Build/O6N/*_GCC/AARCH64/VariableInfo.efi /usr/share/edk2/radxa/orion-o6n/
src/Build/O6N/*_GCC/AARCH64/Shell.efi /usr/share/edk2/radxa/orion-o6n/
src/edk2-non-osi/Platform/CIX/Sky1/FlashTool/* /usr/share/edk2/radxa/orion-o6n/
src/scripts/startup.nsh /usr/share/edk2/radxa/orion-o6n/
