PROJECT ?= edk2-cix

src/tools/gcc/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz:
	mkdir -p src/tools/gcc
	wget -O $@ \
	"https://developer.arm.com/-/media/files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz"

src/tools/gcc/%: src/tools/gcc/%.tar.xz
	tar xvf $< -C src/tools/gcc/

build: build-edk2

.PHONY: build-edk2
build-edk2:
	make --no-print-directory -C src

clean: clean-edk2

.PHONY: clean-edk2
clean-edk2:
	make --no-print-directory -C src clean

.PHONY: buildbox-up
buildbox-up:
	./scripts/run_in_buildbox.sh true

.PHONY: buildbox-deb
buildbox-deb:
	./scripts/run_in_buildbox.sh make --no-print-directory deb

.PHONY: buildbox-o6
buildbox-o6:
	./scripts/run_in_buildbox.sh make --no-print-directory -C src Build/O6/RELEASE_GCC5/cix_flash_all.bin Build/O6/RELEASE_GCC5/cix_flash_ota.bin

.PHONY: buildbox-o6-log
buildbox-o6-log:
	./scripts/capture_build_log.sh build-logs ./scripts/run_in_buildbox.sh make --no-print-directory -C src Build/O6/RELEASE_GCC5/cix_flash_all.bin Build/O6/RELEASE_GCC5/cix_flash_ota.bin

.PHONY: buildbox-metadata
buildbox-metadata:
	./scripts/run_in_buildbox.sh make --no-print-directory -C src print-build-metadata
