/*
 * Copyright (c) 2025 Cix Technology Group Co., Ltd. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* SDEI configuration for ARM platforms */

#include <bl31/ehf.h>
#include <common/debug.h>
#include <services/sdei.h>
#include <lib/utils_def.h>
#include <platform_def.h>

/* Private event mappings */
static sdei_ev_map_t sky1_sdei_private[] = {
	SDEI_DEFINE_EVENT_0(PLAT_SDEI_SGI_PRIVATE),
#if SKY1_IDM_RAS_SUPPORT
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_MMHUB0_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_MMHUB1_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_PCIE0_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_PCIE1_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_SYSHUB0_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_SYSHUB1_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_SMN0_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_IDM_SMN1_EVENT, SDEI_MAPF_CRITICAL),
#endif
#if SKY1_TZC400_IDM_SUPPORT
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_TZC400_0_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_TZC400_1_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_TZC400_2_EVENT, SDEI_MAPF_CRITICAL),
	SDEI_EXPLICIT_EVENT(SDEI_SKY1_TZC400_3_EVENT, SDEI_MAPF_CRITICAL),
#endif
#if SDEI_TEE_EXCEPTION_SUPPORT
	SDEI_EXPLICIT_EVENT(CIX_TEE_EXCEPTION_EVENT, SDEI_MAPF_CRITICAL),
#endif
#if SDEI_TFA_EXCEPTION_SUPPORT
	SDEI_EXPLICIT_EVENT(CIX_TFA_EXCEPTION_EVENT, SDEI_MAPF_CRITICAL),
#endif
};

/* Shared event mappings */
static sdei_ev_map_t sky1_sdei_shared[] = {
#if SDEI_WDT_SUPPORT
	SDEI_SHARED_EVENT(CIX_SDEI_WDT_EVENT, CIX_AP_WDT_INTR,
			  SDEI_MAPF_CRITICAL),
#endif

};

void plat_sdei_setup(void)
{
	INFO("SDEI platform setup\n");
}

/* Export ARM SDEI events */
REGISTER_SDEI_MAP(sky1_sdei_private, sky1_sdei_shared);
