[book]
authors = ["Radxa Limited"]
description = ""
language = "en"
src = "src"
text-direction = "ltr"
title = "edk2-cix"

[output.linkcheck2]

[output.html]
additional-css = ["./theme/css/mdbook-admonish.css"]

[preprocessor.admonish]
command = "scripts/mdbook-admonish.py"

[preprocessor.toc]
command = "scripts/mdbook-toc.sh"
renderer = ["html"]

[preprocessor.cmdrun]
